version: '3.8'
services:
  equity:
    container_name: equity
    image: ${DOCKER_IMAGE:-}
    build: ${DOCKER_BUILD_CONTEXT:-.}
    ports:
      - "4000:4000"
    environment:
      - FLASK_APP=${FLASK_APP:-app.py}
      - FLASK_ENV=${FLASK_ENV:-production}
    restart: unless-stopped
    networks:
      - ${NETWORK_NAME:-default}

networks:
  default:
    driver: bridge
  web:
    external: ${NETWORK_EXTERNAL:-false}