version: '3.8'
services:
  web:
    build: .
    ports:
      - "4000:4000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 